import type { Metadata, Viewport } from "next";
import { NavBar } from "@/components/navBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ["nextjs", "react", "typescript"],
};

export const viewport: Viewport = {
  themeColor: "#e6effc",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <NavBar />
        <main className="flex-1 flex items-center justify-center">
          {children}
        </main>

        <hr />
        <footer className="footer">
          &copy; 2026 - {new Date().getFullYear()} JobGenius. All rights
          reserved.
        </footer>
      </body>
    </html>
  );
}
