soft_skills = [
    "communication",
    "teamwork",
    "problem-solving",
    "adaptability",
    "time management",
    "critical thinking",
    "leadership",
    "creativity",
    "emotional intelligence",
    "work ethic",
    "interpersonal skills",
    "conflict resolution",
    "decision making",
    "stress management",
    "collaboration",
]

it_skills = [
    "python",
    "java",
    "javascript",
    "c++",
    "sql",
    "html",
    "css",
    "react",
    "angular",
    "node.js",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "linux",
    "git",
]

business_skills = [
    "project management",
    "data analysis",
    "marketing",
    "sales",
    "finance",
    "customer service",
    "business development",
    "strategic planning",
    "negotiation",
    "supply chain management",
    "human resources",
]