SPOKEN_LANGUAGES = [
    "english",
    "spanish",
    "french",
    "german",
    "italian",
    "portuguese",
    "russian",
    "chinese",
    "japanese",
    "korean",
    "arabic",
    "hindi",
    "bengali",
    "urdu",
    "punjabi",
    "marathi",
    "telugu",
    "kannada",
    "malayalam",
    "tamil",
    "thai",
    "vietnamese",
    "indonesian",
    "malaysian",
    "filipino",
]

PROFICIENCY_LEVELS = [
    "native",
    "fluent",
    "full professional",
    "professional",
    "advanced",
    "proficient",
    "intermediate",
    "conversational",
    "working",
    "basic",
    "beginner",
    "elementary",
    "limited",
]